### ISSUE TITLE
Check Gatsby Migration Guide for missed changes

### ISSUE THREAD

**Issue by natterstefan** [natterstefan/react-trello-multiboard-page#3]
## Tasks

- [ ] read through https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2
- [ ] update [layout component](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#update-layout-component)
- [ ] check out https://github.com/gatsbyjs/gatsby/issues/2116#issuecomment-416549063
- [ ] release
